// <auto-generated />
using System;
using HealthApp_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthApp_Backend.Migrations
{
    [DbContext(typeof(HealthAppDbContext))]
    [Migration("20241003104727_Weight")]
    partial class Weight
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.1.24451.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthApp_Backend.Models.DomainModels.FoodItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("carbAmount")
                        .HasColumnType("real");

                    b.Property<float>("fatAmount")
                        .HasColumnType("real");

                    b.Property<int>("kcalAmount")
                        .HasColumnType("int");

                    b.Property<string>("measurement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("proteinAmount")
                        .HasColumnType("real");

                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3b2cc595-b071-4602-82e5-869f58e84ab7"),
                            carbAmount = 0f,
                            fatAmount = 0f,
                            kcalAmount = 52,
                            measurement = "100g",
                            name = "Apple",
                            proteinAmount = 0.3f,
                            userId = new Guid("3b2dc595-b071-4602-82e5-869f58e84ab7")
                        },
                        new
                        {
                            Id = new Guid("4eae13c3-408a-42e0-b334-d61c9ad99077"),
                            carbAmount = 0f,
                            fatAmount = 0f,
                            kcalAmount = 89,
                            measurement = "100g",
                            name = "Banana",
                            proteinAmount = 1.1f,
                            userId = new Guid("3b2dc595-b071-4602-82e5-869f58e84ab7")
                        },
                        new
                        {
                            Id = new Guid("dbaf0f17-3886-4954-a093-c0872fb3c8c1"),
                            carbAmount = 0f,
                            fatAmount = 0f,
                            kcalAmount = 47,
                            measurement = "100g",
                            name = "Orange",
                            proteinAmount = 1f,
                            userId = new Guid("3b2dc595-b071-4602-82e5-869f58e84ab7")
                        },
                        new
                        {
                            Id = new Guid("75bbd1bb-9b67-40ad-bac4-c38fdbf86c02"),
                            carbAmount = 0f,
                            fatAmount = 0f,
                            kcalAmount = 50,
                            measurement = "100g",
                            name = "Pineapple",
                            proteinAmount = 0.5f,
                            userId = new Guid("3b2cd595-b071-4602-82e5-869f58e84ab7")
                        });
                });

            modelBuilder.Entity("HealthApp_Backend.Models.DomainModels.ShoppingList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("KcalGoal")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("carbCurrent")
                        .HasColumnType("int");

                    b.Property<int>("carbGoal")
                        .HasColumnType("int");

                    b.Property<int>("fatCurrent")
                        .HasColumnType("int");

                    b.Property<int>("fatGoal")
                        .HasColumnType("int");

                    b.Property<int>("kcalCurrent")
                        .HasColumnType("int");

                    b.Property<bool>("kcalMax")
                        .HasColumnType("bit");

                    b.Property<float>("proteinCurrent")
                        .HasColumnType("real");

                    b.Property<int>("proteinGoal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ShoppingLists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3b2cc595-b071-4602-82e5-869f58e84ab7"),
                            CreatedOn = new DateTime(2024, 10, 3, 12, 47, 26, 664, DateTimeKind.Local).AddTicks(8288),
                            KcalGoal = 2000,
                            UserId = new Guid("3b2cd595-b071-4602-82e5-869f58e84ab7"),
                            carbCurrent = 0,
                            carbGoal = 0,
                            fatCurrent = 0,
                            fatGoal = 0,
                            kcalCurrent = 0,
                            kcalMax = true,
                            proteinCurrent = 0f,
                            proteinGoal = 100
                        },
                        new
                        {
                            Id = new Guid("4eae13c3-408a-42e0-b334-d61c9ad99077"),
                            CreatedOn = new DateTime(2024, 10, 3, 12, 47, 26, 667, DateTimeKind.Local).AddTicks(6430),
                            KcalGoal = 2000,
                            UserId = new Guid("3b2cd595-b071-4602-82e5-869f58e84ab7"),
                            carbCurrent = 0,
                            carbGoal = 0,
                            fatCurrent = 0,
                            fatGoal = 0,
                            kcalCurrent = 0,
                            kcalMax = true,
                            proteinCurrent = 0f,
                            proteinGoal = 100
                        },
                        new
                        {
                            Id = new Guid("dbaf0f17-3886-4954-a093-c0872fb3c8c1"),
                            CreatedOn = new DateTime(2024, 10, 3, 12, 47, 26, 667, DateTimeKind.Local).AddTicks(6492),
                            KcalGoal = 2000,
                            UserId = new Guid("3b2cd595-b071-4602-82e5-869f58e84ab7"),
                            carbCurrent = 0,
                            carbGoal = 0,
                            fatCurrent = 0,
                            fatGoal = 0,
                            kcalCurrent = 0,
                            kcalMax = true,
                            proteinCurrent = 0f,
                            proteinGoal = 100
                        },
                        new
                        {
                            Id = new Guid("75bbd1bb-9b67-40ad-bac4-c38fdbf86c02"),
                            CreatedOn = new DateTime(2024, 10, 3, 12, 47, 26, 667, DateTimeKind.Local).AddTicks(6497),
                            KcalGoal = 2000,
                            UserId = new Guid("3b2cd595-b071-4602-82e5-869f58e84ab7"),
                            carbCurrent = 0,
                            carbGoal = 0,
                            fatCurrent = 0,
                            fatGoal = 0,
                            kcalCurrent = 0,
                            kcalMax = true,
                            proteinCurrent = 0f,
                            proteinGoal = 100
                        });
                });

            modelBuilder.Entity("HealthApp_Backend.Models.DomainModels.ShoppingListFoodItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShoppingListId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("ShoppingListId");

                    b.ToTable("ShoppingListFoodItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f77c44d8-7318-4d81-9bd3-cfe6630d3020"),
                            FoodItemId = new Guid("3b2cc595-b071-4602-82e5-869f58e84ab7"),
                            ShoppingListId = new Guid("3b2cc595-b071-4602-82e5-869f58e84ab7")
                        },
                        new
                        {
                            Id = new Guid("0ce05fb2-b587-480a-b7e9-27f6cc22c760"),
                            FoodItemId = new Guid("4eae13c3-408a-42e0-b334-d61c9ad99077"),
                            ShoppingListId = new Guid("3b2cc595-b071-4602-82e5-869f58e84ab7")
                        },
                        new
                        {
                            Id = new Guid("b9abd736-8817-4117-abcc-c4f320b8fe71"),
                            FoodItemId = new Guid("dbaf0f17-3886-4954-a093-c0872fb3c8c1"),
                            ShoppingListId = new Guid("4eae13c3-408a-42e0-b334-d61c9ad99077")
                        },
                        new
                        {
                            Id = new Guid("d15ce629-15ad-4675-b5a1-2d3867e55b8f"),
                            FoodItemId = new Guid("75bbd1bb-9b67-40ad-bac4-c38fdbf86c02"),
                            ShoppingListId = new Guid("75bbd1bb-9b67-40ad-bac4-c38fdbf86c02")
                        });
                });

            modelBuilder.Entity("HealthApp_Backend.Models.DomainModels.WeightTracker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<float>("WeightGoal")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("WeightTrackers");
                });

            modelBuilder.Entity("HealthApp_Backend.Models.DomainModels.ShoppingListFoodItem", b =>
                {
                    b.HasOne("HealthApp_Backend.Models.DomainModels.FoodItem", "FoodItem")
                        .WithMany("ShoppingListFoodItems")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthApp_Backend.Models.DomainModels.ShoppingList", "ShoppingList")
                        .WithMany("ShoppingListFoodItems")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("HealthApp_Backend.Models.DomainModels.FoodItem", b =>
                {
                    b.Navigation("ShoppingListFoodItems");
                });

            modelBuilder.Entity("HealthApp_Backend.Models.DomainModels.ShoppingList", b =>
                {
                    b.Navigation("ShoppingListFoodItems");
                });
#pragma warning restore 612, 618
        }
    }
}
